{% extends "template/base.phtml" %}
{% block scriptjs %}
    {{ parent() }}
    <script src="assets/js/pages/index.js"></script>
{% endblock %}
{% block title %}Trello Planning Poker{% endblock %}
{% block container %}
<div class="meio-container">
    <div class="jumbotron">
        <center>
            <h1>About Trello Planning Poker</h1>
        </center>
    </div
    <div class="row trello-visible">
        <div class="col-lg-12">
            <h2>About Trello Poker is free!</h2>
            <h2>Needs require extension Chrome Scrum for Trello <a href="https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje?hl=en" target="_blank">https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje?hl=en</a></h2>
        </div>
    </div>
    <hr>
</div>
{% endblock %}

