<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>{% block title %}{% endblock %}</title>
        {% block stylesheet %}
		<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" href="/assets/css/trello.css" />
        {% endblock %}
        {% block scriptjs %}
		<!-- The client library requires jQuery  -->
		<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
		<script src="/assets/js/bootstrap.min.js"></script>
		<script src="https://api.trello.com/1/client.js?key=dc160d013f905ffbb58ae844f79384ad"></script>
		<script src="/assets/js/trello-poker.js"></script>				
        <script src="/assets/js/TrelloRender.js"></script>
        {% endblock %}
    </head>
    <body>		
		<div class="container" >
            <div id="container">
                {% block container %}
                
                {% endblock %}								
			</div>
		</div>
        <div id="data-user"></div>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-54352324-1', 'auto');
            ga('send', 'pageview');

        </script>
    </body>
</html>

